[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p outputs"]

[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"
